### ISSUE TITLE
DB querying

### ISSUE THREAD

**Issue by dangerismycat** [dont-fear-the-repo/fear-the-repo#12]
Query database to add/access data.

**Comment by dangerismycat** [comment]
@melodylu
@sujaypatel16

**Comment by sujaypatel16** [comment]
Created tempDatabaseQueries in /server folder. This is the skeleton of sequelize queries for extracting and inserting data.

**Comment by melodylu** [comment]
Don't forget to add a place in these models for the arrays of children element order!
See comments:

```
const Resume = db.define('Resume', {
  theme: Sequelize.TEXT
  // needs to have order of block children
});

const Block = db.define('Block', {
  jobTitle: Sequelize.STRING,
  startDate: Sequelize.DATE,
  endDate: Sequelize.DATE
  // needs to have order of bullet children
});
```
